production:
  # periodic_cleanup:
  #   class: CleanSoftDeletedRecordsJob
  #   queue: background
  #   args: [ 1000, { batch_size: 500 } ]
  #   schedule: every hour
  unattached_blobs_cleanup:
    command: "ActiveStorage::Blob.unattached.where(created_at: ..2.days.ago).find_each(&:purge_later)"
    schedule: every minute
