global:
  scrape_interval: 15s
  scrape_timeout: 3s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['192.168.0.6:9090']
        labels:
          instance: 'metrics.kamal-testbed'

  - job_name: node
    static_configs:
      - targets: ['192.168.0.3:9100']
        labels:
          instance: 'db.kamal-testbed'
      - targets: ['192.168.0.4:9100']
        labels:
          instance: 'jobs.kamal-testbed'
      - targets: ['192.168.0.2:9100']
        labels:
          instance: 'kamal-testbed'

  - job_name: opentelemetry-collector
    static_configs:
      - targets: ['192.168.0.2:9394']
      - targets: ['192.168.0.4:9394']
